//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace huynh_tien_thang_c2109i2_25_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblStudent()
        {
            this.TblExams = new HashSet<TblExam>();
        }
    
        public int StuId { get; set; }
        public string StuPass { get; set; }
        public string StuAdress { get; set; }
        public string StuPhone { get; set; }
        public string StuEmail { get; set; }
        public string StuName { get; set; }
        public Nullable<int> deptId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblExam> TblExams { get; set; }
    }
}
